version: "3.3"
services:
  real-estate-api-db:
    container_name: real-estate-api-mysql-db
    image: jamielsharief/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "real_estate_api_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - vol-real-estate-api-db:/var/lib/mysql
volumes:
  vol-real-estate-api-db:
